[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "libafc"
version = "0.1.0"
description = "Football analysis library"
authors = [{name = "Your Name", email = "your@email.com"}]
